create table fact_treatments (
	treatment_id varchar(36),
	patient_weight decimal(5,2),
	patient_birth_weight decimal(5,2),
	atc5_code varchar(20),
	prescription_type varchar(20),
	single_unit_dose decimal(10,2),
	dose_unit varchar(20),
	daily_doses decimal(5),
	therapy_intended_duration_known bool,
	therapy_intended_duration decimal(5,2),
	reason_in_notes varchar(20),
	reference_guideline_exists varchar(20),
	drug_according_to_guideline varchar(20),
	dose_according_to_guideline varchar(20),
	duration_according_to_guideline varchar(20),
	roa_according_to_guideline varchar(20),
	outpatient_id varchar(40),
	diagnosis_id varchar(40),
	indication_id varchar(40),
	geographic_id varchar(40),
	survey_id varchar(40),
	department_id varchar(40)
);